INSERT INTO user_role(name) VALUES('ROLE_USER');
INSERT INTO user_role(name) VALUES('ROLE_MANAGEMENT');
INSERT INTO user_role(name) VALUES('ROLE_ADMIN');
INSERT INTO user_role(name) VALUES('ROLE_RESTAURANT');
INSERT INTO user_role(name) VALUES('ROLE_DRIVER');

INSERT INTO category(category) VALUES('Appetizer');
INSERT INTO category(category) VALUES('Mo : Mo');
INSERT INTO category(category) VALUES('Burger');
INSERT INTO category(category) VALUES('Pizza');
INSERT INTO category(category) VALUES('Pasta');
INSERT INTO category(category) VALUES('Biryani');
INSERT INTO category(category) VALUES('Kebabs');
INSERT INTO category(category) VALUES('Chop Suey');
INSERT INTO category(category) VALUES('Sizzler');
INSERT INTO category(category) VALUES('Chefs Special');
INSERT INTO category(category) VALUES('Main Course');
INSERT INTO category(category) VALUES('Dessert');
INSERT INTO category(category) VALUES('Non-Veg Snacks');
INSERT INTO category(category) VALUES('Veg snacks');
INSERT INTO category(category) VALUES('Hard Drinks');
INSERT INTO category(category) VALUES('Soft Drinks');
INSERT INTO category(category) VALUES('Todays Special');


insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('1999-12-02','niranjanthapa@gmail.com','Niranjan','Thapa','','$2a$10$d/4XH0CIbbUN0UtJhk7mT.jCFb/peVBIUgaQmg/G0Q2kkTQrBJUki','9810314784','using','niranjan','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('2000-12-20','robinkarki@gmail.com','Rabindra','Karki','Jung','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810314484','using','robin','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('2002-01-03','ravikhadka@gmail.com','Ravi','Khadka','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810313784','using','ravi','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('2000-10-12','prabeshkhati@gmail.com','Prabesh','Chettri','Khati','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810313284','using','prabesh','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('1990-12-20','abhisekhKhadka@gmail.com','ABhisekh','Khadka','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810214384','using','abhisekh','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('1991-11-20','prashannathapa@gmail.com','prashanna','Thapa','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810224784','using','prashanna','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('1992-10-20','nimasherpa@gmail.com','nima','sherpa','tsering','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814314484','using','tseringnima','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('1993-09-20','nabinshiwakoti@gmail.com','nabin','shiwakoti','Khati','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814313284','using','nabin','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('1994-02-20','nishanbade@gmail.com','nishan','bade','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814314784','using','nishan','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('1995-05-20','rupashresthagmail.com','rupa','shrestha','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814313784','using','rupa','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,username,enabled,locked)  values ('1996-01-20','sudikshyatwayana@gmail.com','sudikshya','twayana','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814214384','using','sudikshya','true','true');

insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_1',1,12,'2023-02-14','10:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_2',1,12,'2023-02-14','14:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_3',1,12,'2023-02-14','07:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_4',1,12,'2023-02-15','10:00','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_5',1,12,'2023-02-15','12:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_6',1,6,'2023-02-15','19:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_7',1,11,'2023-02-16','14:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_8',1,10,'2023-02-16','12:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_9',1,13,'2023-02-12','10:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_10',1,12,'2023-02-13','14:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_11',1,12,'2023-02-17','07:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_12',1,12,'2023-02-17','10:00','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_13',1,12,'2023-02-17','12:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_14',1,12,'2023-02-18','19:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_15',1,12,'2023-02-19','14:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_16',1,12,'2023-02-20','12:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_17',2,12,'2023-02-14','10:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_18',2,12,'2023-02-14','14:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_19',2,12,'2023-02-14','07:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_20',2,12,'2023-02-15','10:00','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_21',2,12,'2023-02-15','12:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_22',2,6,'2023-02-15','19:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_23',2,11,'2023-02-16','14:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_24',2,10,'2023-02-16','12:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_25',2,13,'2023-02-12','10:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_26',2,12,'2023-02-13','14:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_27',2,12,'2023-02-17','07:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_28',2,12,'2023-02-17','10:00','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_29',2,12,'2023-02-17','12:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_30',2,12,'2023-02-18','19:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_31',2,12,'2023-02-19','14:30','DELIVERED');
insert into customer_order(order_id,user_id,total_items,order_date,order_time,status) VALUES ('ORDER_32',2,12,'2023-02-20','12:30','DELIVERED');

insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('1','ORDER_1','2023-02-14','11:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('2','ORDER_2','2023-02-14','15:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('3','ORDER_3','2023-02-14','08:30','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('4','ORDER_4','2023-02-15','10:00','ESEWA','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('5','ORDER_5','2023-02-15','12:30','KHALTI','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('6','ORDER_6','2023-02-15','08:30','PAYPAL','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('7','ORDER_7','2023-02-16','11:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('8','ORDER_8','2023-02-16','15:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('9','ORDER_9','2023-02-12','08:30','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('10','ORDER_10','2023-02-13','11:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('11','ORDER_11','2023-02-17','15:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('12','ORDER_12','2023-02-17','08:30','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('13','ORDER_13','2023-02-12','08:30','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('14','ORDER_14','2023-02-13','11:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('15','ORDER_15','2023-02-17','15:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('16','ORDER_16','2023-02-17','08:30','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('17','ORDER_17','2023-02-14','11:15','','OFFLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('18','ORDER_18','2023-02-14','15:15','KHALTI','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('19','ORDER_19','2023-02-14','08:30','KHALTI','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('20','ORDER_20','2023-02-15','10:00','ESEWA','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('21','ORDER_21','2023-02-15','12:30','KHALTI','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('22','ORDER_22','2023-02-15','08:30','PAYPAL','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('23','ORDER_23','2023-02-16','11:15','ESEWA','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('24','ORDER_24','2023-02-16','15:15','ESEWA','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('25','ORDER_25','2023-02-12','08:30','ESEWA','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('26','ORDER_26','2023-02-13','11:15','KHALTI','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('27','ORDER_27','2023-02-17','15:15','KHALTI','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('28','ORDER_28','2023-02-17','08:30','ESEWA','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('29','ORDER_29','2023-02-12','08:30','ESEWA','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('30','ORDER_30','2023-02-13','11:15','ESEWA','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('31','ORDER_31','2023-02-17','15:15','KHALTI','ONLINE',2000.00,'PAID');
insert into payment(id, order_id, payment_date,payment_time,payment_partner,payment_method,paid_amount,status) values('32','ORDER_32','2023-02-17','08:30','KHALTI','ONLINE',2000.00,'PAID');

insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('1','Nepal','ProvinceNo1','jhapa','bhadrapur','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('2','Nepal','ProvinceNo1','jhapa','bhadrapur','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('3','Nepal','ProvinceNo1','jhapa','bhadrapur','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('4','Nepal','ProvinceNo1','jhapa','bhadrapur','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('5','Nepal','ProvinceNo1','jhapa','bhadrapur','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('6','Nepal','ProvinceNo1','jhapa','bhadrapur','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('7','Nepal','ProvinceNo1','jhapa','bhadrapur','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('8','Nepal','ProvinceNo1','jhapa','bhadrapur','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('9','Nepal','ProvinceNo1','jhapa','bhadrapur','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('10','Nepal','ProvinceNo1','jhapa','bhadrapur','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('11','Nepal','ProvinceNo1','jhapa','bhadrapur','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('12','Nepal','ProvinceNo1','jhapa','bhadrapur','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('13','Nepal','ProvinceNo1','jhapa','bhadrapur','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('14','Nepal','ProvinceNo1','jhapa','bhadrapur','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('15','Nepal','ProvinceNo1','jhapa','bhadrapur','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('16','Nepal','ProvinceNo1','jhapa','chandragadhi','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('17','Nepal','ProvinceNo1','jhapa','chandragadhi','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('18','Nepal','ProvinceNo1','jhapa','chandragadhi','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('19','Nepal','ProvinceNo1','jhapa','chandragadhi','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('20','Nepal','ProvinceNo1','jhapa','chandragadhi','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('21','Nepal','ProvinceNo1','jhapa','chandragadhi','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('22','Nepal','ProvinceNo1','jhapa','chandragadhi','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('23','Nepal','ProvinceNo1','jhapa','chandragadhi','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('24','Nepal','ProvinceNo1','jhapa','chandragadhi','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('25','Nepal','ProvinceNo1','jhapa','chandragadhi','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('26','Nepal','ProvinceNo1','jhapa','chandragadhi','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('27','Nepal','ProvinceNo1','jhapa','chandragadhi','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('28','Nepal','ProvinceNo1','jhapa','chandragadhi','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('29','Nepal','ProvinceNo1','jhapa','chandragadhi','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('30','Nepal','ProvinceNo1','jhapa','chandragadhi','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('31','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('32','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('33','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('34','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('35','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('36','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('37','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('38','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('39','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('40','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('41','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('42','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('43','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('44','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('45','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('46','Nepal','ProvinceNo1','Kanchanpur','Mahendranagar','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('47','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('48','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('49','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('50','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('51','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('52','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('53','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('54','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('55','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('56','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('57','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('58','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('59','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('60','Nepal','ProvinceNo1','Kanchanpur','dodarachadani','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('61','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('62','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('63','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('64','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('65','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('66','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('67','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('68','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('69','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('70','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('71','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('72','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('73','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('74','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('75','Nepal','ProvinceNo3','Kathmandu','Swoyambhu','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('76','Nepal','ProvinceNo3','Kathmandu','Lazimpat','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('77','Nepal','ProvinceNo3','Kathmandu','Lazimpat','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('78','Nepal','ProvinceNo3','Kathmandu','Lazimpat','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('79','Nepal','ProvinceNo3','Kathmandu','Lazimpat','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('80','Nepal','ProvinceNo3','Kathmandu','Lazimpat','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('81','Nepal','ProvinceNo3','Kathmandu','Lazimpat','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('82','Nepal','ProvinceNo3','Kathmandu','Lazimpat','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('83','Nepal','ProvinceNo3','Kathmandu','Lazimpat','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('84','Nepal','ProvinceNo3','Kathmandu','Lazimpat','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('85','Nepal','ProvinceNo3','Kathmandu','Lazimpat','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('86','Nepal','ProvinceNo3','Kathmandu','Lazimpat','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('87','Nepal','ProvinceNo3','Kathmandu','Lazimpat','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('88','Nepal','ProvinceNo3','Kathmandu','Lazimpat','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('89','Nepal','ProvinceNo3','Kathmandu','Lazimpat','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('90','Nepal','ProvinceNo3','Kathmandu','Lazimpat','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('91','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('92','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('93','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('94','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('95','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('96','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('97','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('98','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('99','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('100','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('101','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('102','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('103','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('104','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('105','Nepal','ProvinceNo3','Lalitpur','Bhaisepati','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('106','Nepal','ProvinceNo3','Lalitpur','Patan','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('107','Nepal','ProvinceNo3','Lalitpur','Patan','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('108','Nepal','ProvinceNo3','Lalitpur','Patan','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('109','Nepal','ProvinceNo3','Lalitpur','Patan','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('110','Nepal','ProvinceNo3','Lalitpur','Patan','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('111','Nepal','ProvinceNo3','Lalitpur','Patan','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('112','Nepal','ProvinceNo3','Lalitpur','Patan','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('113','Nepal','ProvinceNo3','Lalitpur','Patan','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('114','Nepal','ProvinceNo3','Lalitpur','Patan','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('115','Nepal','ProvinceNo3','Lalitpur','Patan','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('116','Nepal','ProvinceNo3','Lalitpur','Patan','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('117','Nepal','ProvinceNo3','Lalitpur','Patan','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('118','Nepal','ProvinceNo3','Lalitpur','Patan','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('119','Nepal','ProvinceNo3','Lalitpur','Patan','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('120','Nepal','ProvinceNo3','Lalitpur','Patan','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('121','Nepal','ProvinceNo3','Bhaktapur','Thimi','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('122','Nepal','ProvinceNo3','Bhaktapur','Thimi','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('123','Nepal','ProvinceNo3','Bhaktapur','Thimi','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('124','Nepal','ProvinceNo3','Bhaktapur','Thimi','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('125','Nepal','ProvinceNo3','Bhaktapur','Thimi','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('126','Nepal','ProvinceNo3','Bhaktapur','Thimi','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('127','Nepal','ProvinceNo3','Bhaktapur','Thimi','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('128','Nepal','ProvinceNo3','Bhaktapur','Thimi','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('129','Nepal','ProvinceNo3','Bhaktapur','Thimi','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('130','Nepal','ProvinceNo3','Bhaktapur','Thimi','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('131','Nepal','ProvinceNo3','Bhaktapur','Thimi','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('132','Nepal','ProvinceNo3','Bhaktapur','Thimi','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('133','Nepal','ProvinceNo3','Bhaktapur','Thimi','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('134','Nepal','ProvinceNo3','Bhaktapur','Thimi','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('135','Nepal','ProvinceNo3','Bhaktapur','Thimi','15');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('136','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','1');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('137','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','2');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('138','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','3');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('139','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','4');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('140','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','5');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('141','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','6');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('142','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','7');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('143','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','8');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('144','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','9');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('145','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','10');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('146','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','11');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('147','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','12');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('148','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','13');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('149','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','14');
insert into restaurant_address(address_id,country,state,district,street_name,street_number) values ('150','Nepal','ProvinceNo3','Bhaktapur','Ghathaghar','15');

insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_1','+977','atburgerhouselazimpat@gmail.com','AT Burger House and Crunchy Fried Chicken','9823456789','014880123','76','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_2','+977','pepepizalazimpat@gmail.com','Pepe Pizza Lazimpat','9813456789','014580123','77','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_3','+977','haddibiryani@gmail.com','Hadi Biryani','9823426789','014881123','81','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_4','+977','fatisbiryani@gmail.com','Fatis Biryani','9824456789','014840123','86','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_5','+977','chimneykitchen@gmail.com','Chimney Kitchen','9826765789','014810123','98','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_6','+977','thechimneyrestaurant@gmail.com','The Chimney Restaurant','9823356789','014829123','75','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_7','+977','firencrust@gmail.com','Fire and Crust','9827456789','014882123','75','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_8','+977','workshopeatery@gmail.com','Workshop Eatery','9813756789','014480123','125','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_9','+977','jimbuthakali@gmail.com','Jimbu Thakali','9843456789','015880123','75','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_10','+977','lesherparestauarant@gmail.com','Le Sherpa Restaurant','9823455789','014880173','82','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_11','+977','bagaanthakalirestaurant@gmail.com','Bagan Thakali Restaurant','9812456789','014540123','93','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_12','+977','roadhousecafethamal@gmail.com','Roadhouse Cafe','9854456789','016880123','62','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_13','+977','roadhousecafejhamsikhel@gmail.com','Roadhouse Cafe','9823926789','014980223','119','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_14','+977','shambalarestaurant@gmail.com','Shambala Restaurant','9813446789','01-4678923','67','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_15','+977','pizzahutdurbarmarg@gmail.com','Pizza Hut','9826756789','014889123','90','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_16','+977','herbewandshawrestaurant@gmail.com','Herbew and Shaw','9821956789','014182123','123','ONCONTRACT');
insert into restaurant(restaurant_id, country_code,email,name,phone_number,telephone_number,address_id,status) VALUES('RESTAURANT_17','+977','americanexpresscafe@gmail.com','American Express Cafe','9812956789','01-5182123','125','ONCONTRACT');


insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (1,'RESTAURANT_1','9:00','22:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (2,'RESTAURANT_2','10:00','20:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (3,'RESTAURANT_3','11:00','21:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (4,'RESTAURANT_4','12:00','23:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (5,'RESTAURANT_5','13:00','00:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (6,'RESTAURANT_6','07:00','14:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (7,'RESTAURANT_7','10:00','17:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (8,'RESTAURANT_8','11:00','16:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (9,'RESTAURANT_9','12:00','20:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (10,'RESTAURANT_10','13:00','21:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (11,'RESTAURANT_11','08:00','21:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (12,'RESTAURANT_12','09:00','21:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (13,'RESTAURANT_13','10:00','21:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (14,'RESTAURANT_14','11:00','21:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (15,'RESTAURANT_15','10:00','21:00','The menu consists of food items and the service and VAT are inclusive');
insert into menu(menu_id,restaurant_id,opening_time,closing_time,description) VALUES (16,'RESTAURANT_16','12:00','21:00','The menu consists of food items and the service and VAT are inclusive');

insert into meal(meal_id,meal) VALUES(1,'Breakfast');
insert into meal(meal_id,meal) VALUES(2,'Lunch');
insert into meal(meal_id,meal) VALUES(3,'Dinner');
insert into meal(meal_id,meal) VALUES(4,'Supper');
insert into meal(meal_id,meal) VALUES(5,'Brunch');
insert into meal(meal_id,meal) VALUES(6,'AllTime');

insert into food(food_id,name) VALUES(1,'Chicken Mo : Mo');
insert into food(food_id,name) VALUES(2,'Buff Mo : Mo');
insert into food(food_id,name) VALUES(3,'Veg Mo : Mo');
insert into food(food_id,name) VALUES(4,'Chicken Fried Mo : Mo');
insert into food(food_id,name) VALUES(5,'Chicken Kothey Mo : Mo');
insert into food(food_id,name) VALUES(6,'Buff Fried Mo : Mo');
insert into food(food_id,name) VALUES(7,'Buff Kothey Mo : Mo');
insert into food(food_id,name) VALUES(8,'Veg Fried Mo : Mo');
insert into food(food_id,name) VALUES(9,'Veg Kothey Mo : Mo');
insert into food(food_id,name) VALUES(10,'Buff C Mo : Mo');
insert into food(food_id,name) VALUES(11,'Veg C Mo : Mo');
insert into food(food_id,name) VALUES(12,'Chicken C Mo : Mo');
insert into food(food_id,name) VALUES(13,'Chicken Sausage BBQ');
insert into food(food_id,name) VALUES(14,'Hawaiian Chicken');
insert into food(food_id,name) VALUES(15,'Chicken Pepperoni');
insert into food(food_id,name) VALUES(16,'Italian Chicken Delight');
insert into food(food_id,name) VALUES(17,'Malai Chicken Tikka');
insert into food(food_id,name) VALUES(18,'Spiced Chicken Meatball');
insert into food(food_id,name) VALUES(19,'Margherita');
insert into food(food_id,name) VALUES(20,'Mushroom Sauted');
insert into food(food_id,name) VALUES(21,'Double Cheese');
insert into food(food_id,name) VALUES(22,'Spiced Paneer');
insert into food(food_id,name) VALUES(23,'Mixed Cheese');
insert into food(food_id,name) VALUES(24,'Mushroom');
insert into food(food_id,name) VALUES(25,'Cheese Burger (Single)');
insert into food(food_id,name) VALUES(26,'Cheese Burger (Double)');
insert into food(food_id,name) VALUES(27,'Chicken Salami (Double)');
insert into food(food_id,name) VALUES(28,'Chicken BBQ (Single)');
insert into food(food_id,name) VALUES(29,'Chicken BBQ (Double)');
insert into food(food_id,name) VALUES(30,'Spicy Chicken (Single)');
insert into food(food_id,name) VALUES(31,'Spicy Chicken (Double)');
insert into food(food_id,name) VALUES(32,'Chicken Ham (Single)');
insert into food(food_id,name) VALUES(33,'Chicken ham (Double)');
insert into food(food_id,name) VALUES(34,'Bacon Cheese (Single)');
insert into food(food_id,name) VALUES(35,'Bacon Cheese (Double)');
insert into food(food_id,name) VALUES(36,'Mixed Salami');
insert into food(food_id,name) VALUES(37,'Chicken Bacon');
insert into food(food_id,name) VALUES(38,'Ham');
insert into food(food_id,name) VALUES(39,'Baked Spaghetti');
insert into food(food_id,name) VALUES(40,'Cacio e Pepe Potato Gnocchi');
insert into food(food_id,name) VALUES(41,'Carbonara with Garlic Bread');
insert into food(food_id,name) VALUES(42,'Cacio e Pepe');
insert into food(food_id,name) VALUES(43,'Pasta Puttanesca');
insert into food(food_id,name) VALUES(44,'Lasagna Roll Ups');
insert into food(food_id,name) VALUES(45,'Lasagna Bolognese');
insert into food(food_id,name) VALUES(46,'Lemon Ricotta');
insert into food(food_id,name) VALUES(47,'Creamy Tuscan Sausage');
insert into food(food_id,name) VALUES(48,'Chicken Florentine');
insert into food(food_id,name) VALUES(49,'Spaghetti Lasagna');
insert into food(food_id,name) VALUES(50,'Italian Mac & Cheese');
insert into food(food_id,name) VALUES(51,'Cheesy Ravioli Bake');
insert into food(food_id,name) VALUES(52,'Chicken Piccata');
insert into food(food_id,name) VALUES(53,'American Chop Suey');
insert into food(food_id,name) VALUES(54,'Chinese Chop Suey');
insert into food(food_id,name) VALUES(55,'Peri-Peri Sizzler');
insert into food(food_id,name) VALUES(56,'Barbeque Sizzler');
insert into food(food_id,name) VALUES(57,'Cauliflower Au Gratin Sizzler');
insert into food(food_id,name) VALUES(58,'Chilli Cottage Cheese Sizzler');
insert into food(food_id,name) VALUES(59,'Peri Peri Chicken Sizzler');
insert into food(food_id,name) VALUES(60,'BBQ Chicken Sizller');
insert into food(food_id,name) VALUES(61,'Chicken Alla King Sizzler');
insert into food(food_id,name) VALUES(62,'Chilli Chicken Sizzler');
insert into food(food_id,name) VALUES(63,'Hyderabadi Veg Biryani');
insert into food(food_id,name) VALUES(64,'Hyderabadi Chicken Biryani');
insert into food(food_id,name) VALUES(65,'Awadhi Chicken Biryani');
insert into food(food_id,name) VALUES(66,'Awadhi Veg Briyani');
insert into food(food_id,name) VALUES(67,'Kolkata Veg Biryani');
insert into food(food_id,name) VALUES(68,'Kolkata Chicken Biryani');
insert into food(food_id,name) VALUES(69,'Ambur Veg Biryani');
insert into food(food_id,name) VALUES(70,'Ambur Chicken Biryani');
insert into food(food_id,name) VALUES(71,'Ambur Mutton Biryani');
insert into food(food_id,name) VALUES(72,'Ambur Mixed Biryani');
insert into food(food_id,name) VALUES(73,'Hyderabadi Mutton Biryani');
insert into food(food_id,name) VALUES(74,'Hyderabadi Mixed Biryani');
insert into food(food_id,name) VALUES(75,'Awadhi Mutton Biryani');
insert into food(food_id,name) VALUES(76,'Awadhi Mixed Biryani');
insert into food(food_id,name) VALUES(77,'Kolkata Mixed Biryani');
insert into food(food_id,name) VALUES(78,'Kolkata Mutton Biryani');
insert into food(food_id,name) VALUES(79,'Chicken Adana Kebab');
insert into food(food_id,name) VALUES(80,'Beyti Kebab');
insert into food(food_id,name) VALUES(81,'Adani Kebab');
insert into food(food_id,name) VALUES(82,'Chicken Sis Kebab');
insert into food(food_id,name) VALUES(83,'Turkish Pork Sis Kebab');
insert into food(food_id,name) VALUES(84,'Turkish Chicken Sis Kebab');
insert into food(food_id,name) VALUES(85,'Mutton Sis Kebab');
insert into food(food_id,name) VALUES(86,'Pork Sis Kebab');
insert into food(food_id,name) VALUES(87,'Mix Sis Kebab');
insert into food(food_id,name) VALUES(88,'Pork Adana Kebab');
insert into food(food_id,name) VALUES(89,'Mutton Adana Kebab');
insert into food(food_id,name) VALUES(90,'Mixed Adana Kebab');
insert into food(food_id,name) VALUES(91,'Butter Chicken');
insert into food(food_id,name) VALUES(92,'Palak Paneer');
insert into food(food_id,name) VALUES(93,'Rogan Josh');
insert into food(food_id,name) VALUES(94,'Grilled Chicken With Fresh Cherry Salsa');
insert into food(food_id,name) VALUES(95,'Salmon Chowder with Leeks and Potatoes');
insert into food(food_id,name) VALUES(96,'Skinny Skillet CHicken Cordon Bleu');
insert into food(food_id,name) VALUES(97,'CHipotle Pulled Pork Masa Cakes');
insert into food(food_id,name) VALUES(98,'SZECHUAN/ SICHUAN SALT & PEPPER PORK STIR FRY');
insert into food(food_id,name) VALUES(99,'Braised Chicken Legs With Grapes and Fennel');
insert into food(food_id,name) VALUES(100,'Seared Scallops With Brown Butter and Lemon Pan Sauce');
insert into food(food_id,name) VALUES(101,'Grilled Pork Spareribs With Soda Bottle Barbecue Sauce');
insert into food(food_id,name) VALUES(102,'Caesar Salad Roast Chicken');
insert into food(food_id,name) VALUES(103,'Grilled Coconut Shrimp With Shishito Peppers');
insert into food(food_id,name) VALUES(104,'Marinated Chicken Breasts With Grilled Pineapple Relish');
insert into food(food_id,name) VALUES(105,'Braised Chile-Marmalade Duck Legs With Brussels Sprouts');
insert into food(food_id,name) VALUES(106,'Tamarind-Glazed Black Bass With Coconut-Herb Salad');
insert into food(food_id,name) VALUES(107,'Miso-Butter Roast Chicken With Acorn Squash Panzanella');
insert into food(food_id,name) VALUES(108,'Grilled Jerk Tofu and Plantains With Mango Salsa');
insert into food(food_id,name) VALUES(109,'Chicken and Potato Gratin With Brown Butter Cream');
insert into food(food_id,name) VALUES(110,'Stuffed Eggplants and Zucchini in a Rich Tomato Sauce (Baatingan w Kusaa Bil Banadoura)');
insert into food(food_id,name) VALUES(111,'Spicy Tamarind-Glazed Grilled Chicken Wings');
insert into food(food_id,name) VALUES(112,'Chicken Thali');
insert into food(food_id,name) VALUES(113,'Mutton Thali');
insert into food(food_id,name) VALUES(114,'Veg Thali');
insert into food(food_id,name) VALUES(115,'Chicken Thakali Khana Set');
insert into food(food_id,name) VALUES(116,'Veg Thakali Khana Set');
insert into food(food_id,name) VALUES(117,'Mutton Thakali Khana Set');
insert into food(food_id,name) VALUES(117,'Steamed Fish With Ginger and Scallions');
insert into food(food_id,name) VALUES(118,'Pork Chops With Fig and Grape Agrodolce');
insert into food(food_id,name) VALUES(119,'Charred Chicken With Sweet Potatoes and Oranges');
insert into food(food_id,name) VALUES(120,'Slow-Roasted Salmon in Parchment Paper');
insert into food(food_id,name) VALUES(121,'Roast Chicken With Harissa and Schmaltz');
insert into food(food_id,name) VALUES(122,'Pork Chops with Celery and Almond Salad');
insert into food(food_id,name) VALUES(123,'Fried Whole Fish With Tomatillo Sauce');
insert into food(food_id,name) VALUES(124,'Chicken Sausage');
insert into food(food_id,name) VALUES(125,'Buff Sausage');
insert into food(food_id,name) VALUES(126,'French Fries');
insert into food(food_id,name) VALUES(127,'Chicken Wings');
insert into food(food_id,name) VALUES(128,'Chicken Drumsticks');
insert into food(food_id,name) VALUES(129,'Mustange Aloo');
insert into food(food_id,name) VALUES(130,'Peanut Sadheko');
insert into food(food_id,name) VALUES(131,'Sukuti Sadheko');
insert into food(food_id,name) VALUES(132,'Mutton Sadheko');
insert into food(food_id,name) VALUES(133,'Buff Choila');
insert into food(food_id,name) VALUES(134,'Chicken Choila');
insert into food(food_id,name) VALUES(135,'Mushroom Sadheko');
insert into food(food_id,name) VALUES(136,'Mushroom Choila');
insert into food(food_id,name) VALUES(137,'Potato Chips');
insert into food(food_id,name) VALUES(138,'Buff Chilly');
insert into food(food_id,name) VALUES(139,'Chicken Chilly');
insert into food(food_id,name) VALUES(140,'Chicken Tartar');
insert into food(food_id,name) VALUES(141,'Chicken Popcorn');
insert into food(food_id,name) VALUES(124,'Banana Lassi');
insert into food(food_id,name) VALUES(125,'Vanilla lassi');
insert into food(food_id,name) VALUES(126,'Mixed Lassi');
insert into food(food_id,name) VALUES(127,'Vanilla Milkshak');
insert into food(food_id,name) VALUES(128,'Chocolate Milkshake');
insert into food(food_id,name) VALUES(129,'Strawberry Milkshake');
insert into food(food_id,name) VALUES(130,'Tropical Smoothie');
insert into food(food_id,name) VALUES(131,'Strawberry Banana Smoothie');
insert into food(food_id,name) VALUES(132,'Raspberry Smoothie');
insert into food(food_id,name) VALUES(133,'Peach Smoothie');
insert into food(food_id,name) VALUES(134,'Berry Smoothie');
insert into food(food_id,name) VALUES(135,'Mango Smoothie');
insert into food(food_id,name) VALUES(136,'Watermelon Smoothie');
insert into food(food_id,name) VALUES(137,'Potato Chips');
insert into food(food_id,name) VALUES(138,'Buff Chilly');
insert into food(food_id,name) VALUES(139,'Chicken Chilly');
insert into food(food_id,name) VALUES(140,'Chicken Tartare');
insert into food(food_id,name) VALUES(141,'Chicken Popcorn');
insert into food(food_id,name) VALUES(142,'Crossiant');
insert into food(food_id,name) VALUES(143,'Crossiant with Chocolate');
insert into food(food_id,name) VALUES(144,'Cheese Cake');
insert into food(food_id,name) VALUES(145,'Red Velvet');
insert into food(food_id,name) VALUES(146,'Brownie with Icecream');
insert into food(food_id,name) VALUES(147,'Blueberry Cake');
insert into food(food_id,name) VALUES(148,'Mango and coconut soufflé');
insert into food(food_id,name) VALUES(149,'Carrot Cake');
insert into food(food_id,name) VALUES(150,'XL lemon meringue pie');
insert into food(food_id,name) VALUES(151,'Pineapple Ravioli');
insert into food(food_id,name) VALUES(152,'Blackberry Cheesecake');
insert into food(food_id,name) VALUES(153,'Chocolate Caramel Hazelnut Pie');
insert into food(food_id,name) VALUES(154,'Warm Pineapple Sundaes with Rum Sauce');
insert into food(food_id,name) VALUES(155,'Gajar Halwa');
insert into food(food_id,name) VALUES(156,'Mango kulfi');
insert into food(food_id,name) VALUES(157,'Chocolate Peanut Butter Shake');
insert into food(food_id,name) VALUES(158,'Butter Pecan Pumpkin Pie');
insert into food(food_id,name) VALUES(159,'Nutty Caramel Ice Cream Cake');
insert into food(food_id,name) VALUES(160,'Margarita Floats');

insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_1',1,1,6,2,200,0,4.1,'Dumpling containing minced chicken keema filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_2',1,2,6,2,180,0,4.2,'Dumpling containing minced Buff keema filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_3',1,3,6,2,160,0,4.4,'Dumpling containing minced mixed vegetables filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_4',1,4,6,2,220,0,4.5,'Deep Fried Dumpling containing minced Chicken keema filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_5',1,5,6,2,200,0,4.6,'Pan Fried Dumpling containing minced Chicken keema filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_6',1,6,6,2,180,0,4.1,'Deep Fried Dumpling containing minced Buff keema filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_7',1,7,6,2,200,0,3.1,'Pan Fried Dumpling containing minced Chicken keema filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_8',1,8,6,2,200,0,3,'Deep Fried Dumpling containing minced mixed vegetables filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_9',1,9,6,2,200,0,4.6,'Pan Fried Dumpling containing minced mixed vegetables filing served with special achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_10',1,10,6,2,220,0,2.6,'Deep Fried Dumpling containing minced Buff keema filing dipped with hot and spicy sauce');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_11',1,11,6,2,180,0,2.3,'Deep Fried Dumpling containing minced mixed vegetable filing dipped with hot and spicy sauce');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_12',1,12,6,2,210,0,2.4,'Deep Fried Dumpling containing minced Chicken keema filing dipped with hot and spicy sauce');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_13',1,13,6,4,565,0,4.0,'This vibrant, thin crust made with vegetables is loaded with real, high quality sweet potato to provide a perfect foundation for our tangy BBQ Chicken Sausage pizza. Topped with zesty BBQ sauce, sliced red onions, delicious chicken sausage and a special blend rBST-free mozzarella and yellow cheddar, this pizza is an adventure for your taste buds.Our unexpected taste combinations elevate pizza beyond the ordinary. This couldn’t be more evident than with our new line of thin crusts made with vegetables, each paired with distinct toppings. Your flavor adventure awaits!');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_14',1,14,6,4,625,0,4.1,'Thin crust vibrant, oven cooked pizza topped with slices of pineapple and chicken');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_15',1,15,6,4,595,0,4.2,'Topped with chicken pepperoni,you can enjoy the pure flavor of chicken covered with a layer of cheese');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_16',1,16,6,4,725,0,4.3,'Chicken, creamy garlic sauce, fresh tomatoes, mushrooms, onions and chopped garlic.');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_17',1,17,6,4,655,0,4.4,'Malai Tikka Pizza is a continuation of combining the tastes of chicken tikka with pizza. ');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_81',2,1,6,2,200,0,4.0,'Chicken Dumpling with timmur Achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_82',2,2,6,2,180,0,4.0,'Buff Dumpling with Timmur achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_83',2,3,6,2,160,0,4.0,'Mixed Vegetables Dumpling with Timur achar');
insert into menu_food(menu_food_id,menu_id,food_id,meal_id,category_id,price,discount_percentage,rating,description) VALUES('MENU_FOOD_84',2,4,6,2,220,0,4.0,'Fried Chicken Dumplings with minced Rice');

insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_1','ORDER_1','MENU_FOOD_1',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_2','ORDER_1','MENU_FOOD_13',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_3','ORDER_1','MENU_FOOD_12',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_4','ORDER_1','MENU_FOOD_17',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_5','ORDER_2','MENU_FOOD_81',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_6','ORDER_2','MENU_FOOD_3',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_7','ORDER_2','MENU_FOOD_9',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_8','ORDER_2','MENU_FOOD_12',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_9','ORDER_2','MENU_FOOD_15',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_10','ORDER_3','MENU_FOOD_3',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_11','ORDER_3','MENU_FOOD_4',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_12','ORDER_3','MENU_FOOD_5',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_13','ORDER_3','MENU_FOOD_6',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_14','ORDER_3','MENU_FOOD_7',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_15','ORDER_4','MENU_FOOD_8',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_16','ORDER_4','MENU_FOOD_9',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_17','ORDER_4','MENU_FOOD_10',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_18','ORDER_4','MENU_FOOD_11',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_19','ORDER_5','MENU_FOOD_12',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_20','ORDER_5','MENU_FOOD_13',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_21','ORDER_5','MENU_FOOD_14',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_22','ORDER_5','MENU_FOOD_15',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_23','ORDER_5','MENU_FOOD_16',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_24','ORDER_6','MENU_FOOD_81',4);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_25','ORDER_6','MENU_FOOD_82',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_26','ORDER_6','MENU_FOOD_83',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_27','ORDER_6','MENU_FOOD_84',4);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_28','ORDER_7','MENU_FOOD_17',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_29','ORDER_7','MENU_FOOD_1',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_30','ORDER_7','MENU_FOOD_2',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_31','ORDER_7','MENU_FOOD_4',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_32','ORDER_7','MENU_FOOD_5',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_33','ORDER_7','MENU_FOOD_6',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_34','ORDER_7','MENU_FOOD_7',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_35','ORDER_8','MENU_FOOD_8',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_36','ORDER_8','MENU_FOOD_9',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_37','ORDER_8','MENU_FOOD_10',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_38','ORDER_8','MENU_FOOD_11',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_39','ORDER_8','MENU_FOOD_12',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_40','ORDER_8','MENU_FOOD_13',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_41','ORDER_9','MENU_FOOD_15',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_42','ORDER_9','MENU_FOOD_16',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_43','ORDER_9','MENU_FOOD_17',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_44','ORDER_9','MENU_FOOD_2',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_45','ORDER_9','MENU_FOOD_5',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_46','ORDER_10','MENU_FOOD_1',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_47','ORDER_10','MENU_FOOD_2',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_48','ORDER_10','MENU_FOOD_3',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_49','ORDER_10','MENU_FOOD_4',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_50','ORDER_10','MENU_FOOD_5',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_51','ORDER_10','MENU_FOOD_6',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_52','ORDER_11','MENU_FOOD_6',4);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_53','ORDER_11','MENU_FOOD_7',4);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_54','ORDER_11','MENU_FOOD_8',4);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_55','ORDER_12','MENU_FOOD_9',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_56','ORDER_12','MENU_FOOD_10',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_57','ORDER_12','MENU_FOOD_11',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_58','ORDER_12','MENU_FOOD_11',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_59','ORDER_13','MENU_FOOD_12',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_60','ORDER_13','MENU_FOOD_13',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_61','ORDER_13','MENU_FOOD_14',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_62','ORDER_13','MENU_FOOD_15',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_63','ORDER_14','MENU_FOOD_16',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_64','ORDER_14','MENU_FOOD_17',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_65','ORDER_14','MENU_FOOD_1',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_66','ORDER_14','MENU_FOOD_5',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_67','ORDER_14','MENU_FOOD_6',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_68','ORDER_14','MENU_FOOD_7',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_69','ORDER_13','MENU_FOOD_81',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_70','ORDER_13','MENU_FOOD_82',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_71','ORDER_13','MENU_FOOD_83',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_72','ORDER_13','MENU_FOOD_84',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_73','ORDER_14','MENU_FOOD_1',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_74','ORDER_14','MENU_FOOD_2',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_75','ORDER_14','MENU_FOOD_3',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_76','ORDER_14','MENU_FOOD_4',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_77','ORDER_14','MENU_FOOD_5',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_78','ORDER_14','MENU_FOOD_6',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_79','ORDER_15','MENU_FOOD_7',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_80','ORDER_15','MENU_FOOD_8',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_81','ORDER_15','MENU_FOOD_9',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_82','ORDER_15','MENU_FOOD_10',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_83','ORDER_15','MENU_FOOD_11',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_84','ORDER_15','MENU_FOOD_12',2);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_85','ORDER_16','MENU_FOOD_13',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_86','ORDER_16','MENU_FOOD_14',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_87','ORDER_16','MENU_FOOD_15',1);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_88','ORDER_16','MENU_FOOD_16',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_89','ORDER_16','MENU_FOOD_17',3);
insert into order_item(order_item_id,order_id,menu_food_id,quantity) VALUES ('ORDER_ITEM_ID_90','ORDER_16','MENU_FOOD_1',4);